sudo: required

language: generic

services:
    - docker

before_install:
    - docker build -t justjared/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true justjared/docker-react npm run test 
