sudo: required

language: generic

services:
    - docker

before_install:
    - docker build -t justjared/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true justjared/docker-react npm run test 

deploy:
    - provider: elasticbeanstalk
    - region: "us-west-2"
    - app: "docker-react"
    - environment: "DockerReact-env"
    - bucket_name: "elasticbeanstalk-us-west-2-212923204091"
    - bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"

    